-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK b JOIN BOOK_SALES bs
ON b.BOOK_ID = bs.BOOK_ID 
JOIN AUTHOR a 
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE '2022-01' = TO_CHAR(bs.SALES_DATE, 'YYYY-MM')
GROUP BY a.AUTHOR_ID, b.CATEGORY, a.AUTHOR_NAME
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;
