-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM
(SELECT ins.animal_id ANIMAL_ID, ins.name NAME, (outs.DATETIME - ins.DATETIME) AS DURATION
FROM ANIMAL_INS ins JOIN ANIMAL_OUTS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
ORDER BY DURATION DESC
FETCH FIRST 2 ROW ONLY)
    

