SELECT R.REST_ID, R.REST_NAME, R.FOOD_TYPE, R.FAVORITES, R.ADDRESS, RR.SCORE
FROM REST_INFO R, 
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW
GROUP BY REST_ID) RR
WHERE R.REST_ID = RR.REST_ID AND R.ADDRESS LIKE '서울%'
ORDER BY RR.SCORE DESC, R.FAVORITES DESC