-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM o.SALES_DATE) AS YEAR , EXTRACT(MONTH FROM o.SALES_DATE) AS MONTH, ui.GENDER AS GENDER, COUNT(DISTINCT ui.USER_ID) AS USERS
FROM USER_INFO ui JOIN ONLINE_SALE o 
ON ui.USER_ID = o.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM o.SALES_DATE), EXTRACT(MONTH FROM o.SALES_DATE), ui.GENDER
ORDER BY EXTRACT(YEAR FROM o.SALES_DATE), EXTRACT(MONTH FROM o.SALES_DATE), ui.GENDER ASC;