-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM (
    SELECT ins.NAME AS NAME, ins.DATETIME AS DATETIME, RANK() OVER (ORDER BY ins.DATETIME) AS RANKING
    FROM ANIMAL_INS ins LEFT JOIN ANIMAL_OUTS outs
    ON ins.ANIMAL_ID = outs.ANIMAL_ID
    WHERE outs.DATETIME IS NULL
)
WHERE RANKING <=3;