SELECT
    h.HISTORY_ID,
    TRUNC(
        (c.DAILY_FEE * (100 - NVL(p.DISCOUNT_RATE, 0)) / 100)
        * (h.END_DATE - h.START_DATE + 1)
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
  ON c.CAR_ID = h.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
  ON c.CAR_TYPE = p.CAR_TYPE
 AND (
        (h.END_DATE - h.START_DATE + 1) BETWEEN 7 AND 29 AND p.DURATION_TYPE = '7일 이상'
     OR (h.END_DATE - h.START_DATE + 1) BETWEEN 30 AND 89 AND p.DURATION_TYPE = '30일 이상'
     OR (h.END_DATE - h.START_DATE + 1) >= 90 AND p.DURATION_TYPE = '90일 이상'
 )
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;
