-- 코드를 입력하세요
SELECT b.WRITER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
WHERE STATUS = 'DONE'
GROUP BY b.WRITER_ID, u.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;