-- 코드를 입력하세요
-- ins.ANIMAL_ID AS ANIMAL_ID, ins.NAME AS NAME
SELECT ins.ANIMAL_ID AS ANIMAL_ID, ins.NAME AS NAME
FROM ANIMAL_INS ins JOIN ANIMAL_OUTS outs
ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE ins.DATETIME > outs.DATETIME
ORDER BY ins.DATETIME ASC