-- 코드를 입력하세요
SELECT DISTINCT(rh.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR rc JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
ON rc.CAR_ID = rh.CAR_ID
WHERE CAR_TYPE = '세단' AND rh.START_DATE >= TO_DATE('2022-10-01','yyyy-mm-dd')
ORDER BY CAR_ID DESC;