-- 코드를 입력하세요
SELECT '/home/grep/src/' || BOARD_ID || '/'|| FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
FROM (
    SELECT uf.BOARD_ID BOARD_ID, uf.FILE_ID FILE_ID, uf.FILE_NAME FILE_NAME, uf.FILE_EXT FILE_EXT, RANK() OVER (ORDER BY ub.VIEWS DESC) AS VIEW_ORDER
FROM USED_GOODS_BOARD ub JOIN USED_GOODS_FILE uf
ON ub.BOARD_ID = uf.BOARD_ID
ORDER BY FILE_ID DESC
)
WHERE VIEW_ORDER <= 1;
