-- 코드를 입력하세요
-- SELECT
-- FROM BOOK_SALES bs JOIN BOOK b
-- WHERE 

SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK_SALES bs JOIN BOOK b
ON bs.BOOK_ID = b.BOOK_ID
WHERE EXTRACT(YEAR FROM bs.SALES_DATE) = '2022' AND EXTRACT(MONTH FROM bs.SALES_DATE) = '1'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC;